[DRAFT] centralized SES service
spartan-stratos/terraform-modules pull request #26
Opened 2024-12-03 09:37 UTC by spartan-haopham

## Summary
Centralized SES services
### Why
Centralization

### What

### Solution

## Types of Changes

- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] 🚀 New feature (non-breaking change which adds functionality)
- [ ] 🕷 Bug fix (non-breaking change which fixes an issue)
- [ ] 👏 Performance optimization (non-breaking change which addresses a performance issue)
- [ ] 🛠 Refactor (non-breaking change which does not change existing behavior or add new functionality)
- [ ] 📗 Library update (non-breaking change that will update one or more libraries to newer versions)
- [ ] 📝 Documentation (non-breaking change that doesn't change code behavior, can skip testing)
- [ ] ✅ Test (non-breaking change related to testing)
- [ ] 🔒 Security awareness (changes that effect permission scope, security scenarios)

## Test Plan

## Related Issues

2024-12-03 09:42 UTC, spartan-ytruong commented on aws/ses/CHANGELOG.md
> +## [0.1.0]() (2024-11-06)
please update the date em

2024-12-04 08:25 UTC, spartan-ytruong requested changes

2024-12-04 08:25 UTC, spartan-ytruong commented on aws/ses/CHANGELOG.md
> +## [0.1.2]() (2024-12-04)
https://github.com/spartan-stratos/terraform-modules/pull/28#discussion_r1868895843

2024-12-04 08:25 UTC, spartan-ytruong commented on aws/ses/examples/complete/main.tf
> +  source            = "../../"
please run `terraform fmt --recursive`

2024-12-04 08:25 UTC, spartan-ytruong commented on aws/ses/examples/complete/outputs.tf
> +}
please add EOL to other files too e

2024-12-04 08:25 UTC, spartan-ytruong commented on aws/ses/main.tf
> +resource "aws_ses_domain_identity" "current" {
you can follow up the convention in `README.md`. we can name it `this` here

2024-12-05 02:48 UTC, spartan-toannhan approved these changes

2024-12-05 02:55 UTC, merged